### ISSUE TITLE
您好，贵项目能否用于分拆构建vue页面的项目？方案如何？

### ISSUE THREAD

**Issue by rhinel** [shuidi-fed/vue-async-manager#2]
对贵项目非常感兴趣！

目前常用的异步组件通常是通过同一个仓库项目中webpack构建将代码拆分出不同的JS文件，作为异步组件的。

那么有没有方案实现，采用同样模板，不同页面单独构建，主项目提供页面注册等功能实现主项目不用重新构建即可接入新页面？

期待回复！

**Comment by HcySunYang** [comment]
你说的可能与微前端架构搭边，不过问题与 vue-async-manager 没有任何关联，因此关闭。
