### ISSUE TITLE
lazy( () => import('file.vue') ) 这种方式有问题

### ISSUE THREAD

**Issue by lisiyizu** [shuidi-fed/vue-async-manager#3]
![image](https://user-images.githubusercontent.com/12014252/61521816-a805e480-aa43-11e9-863d-858232dd213f.png)

![image](https://user-images.githubusercontent.com/12014252/61521914-d71c5600-aa43-11e9-9bbf-098bf5f93fd0.png)

![image](https://user-images.githubusercontent.com/12014252/61521780-945a7e00-aa43-11e9-994d-edd25d695d83.png)

![image](https://user-images.githubusercontent.com/12014252/61521749-7e4cbd80-aa43-11e9-9c3f-4dbd72376856.png)

**Comment by HcySunYang** [comment]
https://github.com/HcySunYang-bot/vue-async-manager-issue-1
我按照你的代码使用 vue-cli3 创建了一个项目，没有任何问题。你可以把这个项目 clone 到本地查看、调试。希望下一次你在给别的项目提交 issue 时，也要提供最小复现，以免浪费彼此的时间。

**Comment by lisiyizu** [comment]
> https://github.com/HcySunYang-bot/vue-async-manager-issue-1
> 我按照你的代码使用 vue-cli3 创建了一个项目，没有任何问题。你可以把这个项目 clone 到本地查看、调试。希望下一次你在给别的项目提交 issue 时，也要提供最小复现，以免浪费彼此的时间。

切换路由，这个问题就复现了，之前没有描述情况，感谢恢复！

![image](https://user-images.githubusercontent.com/12014252/61524927-0e8e0100-aa4a-11e9-951e-441558bf3519.png)

![image](https://user-images.githubusercontent.com/12014252/61524978-26658500-aa4a-11e9-9903-5a2c2de47b5b.png)

![image](https://user-images.githubusercontent.com/12014252/61524978-26658500-aa4a-11e9-9903-5a2c2de47b5b.png)

**Comment by HcySunYang** [comment]
这确实是一个 bug，已修复，使用 vue-async-manager@^0.2.1

**Comment by lisiyizu** [comment]
> 这确实是一个 bug，已修复，使用 vue-async-manager@^0.2.1

非常感谢，👍

**Comment by lisiyizu** [comment]
> 这确实是一个 bug，已修复，使用 vue-async-manager@^0.2.1

测试了 :delay="number"  ，发现设置没有任何效果

**Comment by HcySunYang** [comment]
没有效果就对了，delay 的意思是在多少毫秒之后才展示 loading，如果你的网速很快，如果你没有设置 delay 的话，loading 就会一闪而过；如果你设置了 delay，那么 loading 根本就不会展示。

你可以不设置 delay 的值，然后手动把浏览器的开发者工具中的网络调整为 fast 3G，接着在路由跳转的时候你就可以看到效果了。
