### ISSUE TITLE
请查看一下这个demo，loading状态不消失了。

### ISSUE THREAD

**Issue by sl1673495** [shuidi-fed/vue-async-manager#7]
https://codesandbox.io/s/suspense-lazy-1-vjliu?fontsize=14

我把README上的demo微调了一下，增加了一块Suspense区域，页面上就一致笼罩loading了。

![image](https://user-images.githubusercontent.com/23615778/68445562-3978ac80-0215-11ea-9248-2bb824c498f5.png)

**Comment by HcySunYang** [comment]
Sorry: this project has been deprecated.
